# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: fb54a95
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
active: false
github_repo_name: geldaq
project_description: Data acquisition for PVC gel experiments.
project_email: blake.naccarato@gmail.com
project_name: geldaq
project_owner_github_username: blakeNaccarato
project_owner_name: Daniel Fisher, Blake Naccarato, Abdulkarem Sennain
project_version: 0.0.0
python_version: '3.10'
year_of_project_creation: 2022
