# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d562b92
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
advanced: true
docs_engine: MyST
github_repo_name: geldaq
include_funding: false
project_email: blake.naccarato+geldaq@gmail.com
project_name: geldaq
project_owner_github_username: blakeNaccarato
project_owner_name: Daniel Fisher, Blake Naccarato, Abdulkarem Sennain
python_version: '3.10'
year_of_project_creation: 2022
