# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1f15c17
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
advanced: true
docs_engine: MyST
github_repo_name: geldaq
include_funding: false
override: true
override_codecov: false
override_coveragerc: false
override_env: false
override_flake8: true
override_gitattributes: false
override_gitignore: true
override_isort: true
override_markdownlint: false
override_precommit: false
override_pyrightconfig: false
override_pytest: false
override_sourcery: false
override_update: false
override_vscode_extensions: false
override_vscode_launch: false
override_vscode_settings: false
override_vscode_tasks: false
project_email: blake.naccarato+geldaq@gmail.com
project_name: geldaq
project_owner_github_username: blakeNaccarato
project_owner_name: Daniel Fisher, Blake Naccarato, Abdulkarem Sennain
python_version: '3.10'
use_dvc: false
year_of_project_creation: 2022
