title: geldaq
author: Daniel Fisher, Abdulkarem Sennain, Blake Naccarato
logo: logo.png
execute:
  execute_notebooks: false
bibtex_bibfiles:
  - references.bib
repository:
  url: https://github.com/blakeNaccarato/geldaq
html:
  use_issues_button: true
  use_repository_button: true
