name: "bump"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["requirements.txt"]

jobs:
  bump:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.10"
      # Duplicates some logic to avoid dependency cycle
      - run: |-
          pip install -U pip setuptools wheel
          pip install -r .tools/requirements/requirements_cicd.txt
      - run: "python .tools/scripts/bump_pyproject.py"
      - uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Bump `pyproject.toml` dependencies"
